const { getBlackList } = require('./blacklist-generator');

describe('blacklist-generator', () => {
  describe('getBlackList', () => {
    it('should list all paths including prototypes', () => {
      const blackList = getBlackList();
      expect(blackList).toMatchInlineSnapshot(`
        Object {
          "anchor": true,
          "apply": true,
          "big": true,
          "bind": true,
          "blink": true,
          "bold": true,
          "call": true,
          "charAt": true,
          "charCodeAt": true,
          "codePointAt": true,
          "concat": true,
          "copyWithin": true,
          "endsWith": true,
          "entries": true,
          "every": true,
          "fill": true,
          "filter": true,
          "find": true,
          "findIndex": true,
          "fixed": true,
          "fontcolor": true,
          "fontsize": true,
          "forEach": true,
          "getDate": true,
          "getDay": true,
          "getFullYear": true,
          "getHours": true,
          "getMilliseconds": true,
          "getMinutes": true,
          "getMonth": true,
          "getSeconds": true,
          "getTime": true,
          "getTimezoneOffset": true,
          "getUTCDate": true,
          "getUTCDay": true,
          "getUTCFullYear": true,
          "getUTCHours": true,
          "getUTCMilliseconds": true,
          "getUTCMinutes": true,
          "getUTCMonth": true,
          "getUTCSeconds": true,
          "getYear": true,
          "includes": true,
          "indexOf": true,
          "italics": true,
          "join": true,
          "keys": true,
          "lastIndexOf": true,
          "link": true,
          "localeCompare": true,
          "map": true,
          "match": true,
          "normalize": true,
          "padEnd": true,
          "padStart": true,
          "pop": true,
          "push": true,
          "reduce": true,
          "reduceRight": true,
          "repeat": true,
          "replace": true,
          "reverse": true,
          "search": true,
          "setDate": true,
          "setFullYear": true,
          "setHours": true,
          "setMilliseconds": true,
          "setMinutes": true,
          "setMonth": true,
          "setSeconds": true,
          "setTime": true,
          "setUTCDate": true,
          "setUTCFullYear": true,
          "setUTCHours": true,
          "setUTCMilliseconds": true,
          "setUTCMinutes": true,
          "setUTCMonth": true,
          "setUTCSeconds": true,
          "setYear": true,
          "shift": true,
          "slice": true,
          "small": true,
          "some": true,
          "sort": true,
          "splice": true,
          "split": true,
          "startsWith": true,
          "strike": true,
          "sub": true,
          "substr": true,
          "substring": true,
          "sup": true,
          "toDateString": true,
          "toExponential": true,
          "toFixed": true,
          "toGMTString": true,
          "toISOString": true,
          "toJSON": true,
          "toLocaleDateString": true,
          "toLocaleLowerCase": true,
          "toLocaleTimeString": true,
          "toLocaleUpperCase": true,
          "toLowerCase": true,
          "toPrecision": true,
          "toTimeString": true,
          "toUTCString": true,
          "toUpperCase": true,
          "trim": true,
          "trimEnd": true,
          "trimLeft": true,
          "trimRight": true,
          "trimStart": true,
          "unshift": true,
          "values": true,
        }
      `);
    });
  });
});
