const { getBlackList } = require('./blacklist-generator');

describe('blacklist-generator', () => {
  describe('getBlackList', () => {
    it('should list all paths including prototypes', () => {
      const blackList = getBlackList();
      expect(blackList).toMatchInlineSnapshot(`
        Object {
          "__defineGetter__": true,
          "__defineSetter__": true,
          "__lookupGetter__": true,
          "__lookupSetter__": true,
          "anchor": true,
          "big": true,
          "blink": true,
          "bold": true,
          "charAt": true,
          "charCodeAt": true,
          "codePointAt": true,
          "concat": true,
          "constructor": true,
          "copyWithin": true,
          "endsWith": true,
          "entries": true,
          "every": true,
          "fill": true,
          "filter": true,
          "find": true,
          "findIndex": true,
          "fixed": true,
          "fontcolor": true,
          "fontsize": true,
          "forEach": true,
          "hasOwnProperty": true,
          "includes": true,
          "indexOf": true,
          "isPrototypeOf": true,
          "italics": true,
          "join": true,
          "keys": true,
          "lastIndexOf": true,
          "link": true,
          "localeCompare": true,
          "map": true,
          "match": true,
          "normalize": true,
          "padEnd": true,
          "padStart": true,
          "pop": true,
          "propertyIsEnumerable": true,
          "push": true,
          "reduce": true,
          "reduceRight": true,
          "repeat": true,
          "replace": true,
          "reverse": true,
          "search": true,
          "shift": true,
          "slice": true,
          "small": true,
          "some": true,
          "sort": true,
          "splice": true,
          "split": true,
          "startsWith": true,
          "strike": true,
          "sub": true,
          "substr": true,
          "substring": true,
          "sup": true,
          "toExponential": true,
          "toFixed": true,
          "toLocaleLowerCase": true,
          "toLocaleString": true,
          "toLocaleUpperCase": true,
          "toLowerCase": true,
          "toPrecision": true,
          "toString": true,
          "toUpperCase": true,
          "trim": true,
          "trimEnd": true,
          "trimLeft": true,
          "trimRight": true,
          "trimStart": true,
          "unshift": true,
          "valueOf": true,
          "values": true,
        }
      `);
    });
  });
});
